use_frameworks!

target 'PlayKitVR_Example' do
  pod 'PlayKitVR', :path => '../'

  target 'PlayKitVR_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
