language: objective-c
osx_image: xcode9
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - gem install xcpretty
script:
  - cd PlayKitFramework
  - pod update --repo-update
  - set -o pipefail && xcodebuild -scheme PlayKitFramework -workspace PlayKitFramework.xcworkspace | xcpretty
notifications:
  email:
    recipients:
      - noam.tamim@kaltura.com
      - vadim.kononov@kaltura.com
      - eliza.sapir@kaltura.com
      - gal.orlanczyk@kaltura.com
    on_success: change
    on_failure: always
