use_frameworks!

platform :ios, '9.0'

target 'PlayKitFramework' do
  pod 'PlayKitVR', :path => '../'
  pod 'MetalScope', :git => 'https://github.com/kaltura/MetalScope.git', :branch => 'swift-4.2'
end

